In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato Sales analysis====")
print("\n Sales data shape: ", sales_data.shape)
print("\n Sample data for first three restaurants: ", sales_data[:, 1:])


==== Zomato Sales analysis====

 Sales data shape:  (5, 5)

 Sample data for first three restaurants:  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [4]:
#total sales per year
print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[:, 1:], axis= 0)
print(yearly_total)

#Minimum sales per restaurant
min_sales = np.min(sales_data[:,1:], axis=1)
print(min_sales)

#Maximum sales per year
max_sales_per_year = np.max(sales_data[:, 1:], axis= 0)
print(max_sales_per_year)

#Average sales per restaurant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print(avg_sales)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [5]:
cumsum = np.cumsum(sales_data[:, 1:], axis=1)
print(cumsum)

plt.figure(figsize=(8, 6))
plt.plot(np.mean(cumsum, axis=0))
plt.title("Average cumulative sales per restaurant")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [6]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print("Vector addition: ", vector1 + vector2)

print("\n Multiplication of vector: ", vector1 * vector2)

print("\n Dot product: ",np.dot(vector1, vector2))

Vector addition:  [ 7  9 11 13 15]

 Multiplication of vector:  [ 6 14 24 36 50]

 Dot product:  130
