## Numpy array and basics
learn about numpy

In [7]:
import numpy as np

### creating array from list

In [8]:
arr_1d = np.array([1, 2, 3])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [9]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [10]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
end = time.time()
print("\n List operation time: ", end - start)


 List operation time:  1.2316079139709473


In [15]:
start_np = time.time()
np_array = np.arange(100000000) * 2
print(np_array)
end_np = time.time()
print("\n Numpy operation time: ", end_np - start_np)

[        0         2         4 ... 199999994 199999996 199999998]

 Numpy operation time:  0.7049205303192139


### creating array from scratch

In [12]:
zeros = np.zeros((3, 4))
print("zeros array: \n",zeros)

ones = np.ones((3, 4))
print("ones array: \n",ones)

full = np.full((3, 4), 7)
print("full array: \n",full)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [13]:
random = np.random.random((2, 3))
print(random)

[[0.17941392 0.84720907 0.64146527]
 [0.46549965 0.05281049 0.44539289]]


In [ ]:
sequence = np.arange(0, 10)
print(sequence)

[0 1 2 3 4 5 6 7 8 9]


### Vector, Matrix, Tensor

In [16]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

Vector:  [1 2 3]


In [17]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

Matrix:  [[1 2 3]
 [4 5 6]]


In [19]:
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [27]:
arr = np.array([[1, 2, 3],
                [4, 5, 6.2]])
print(arr)
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Datatype ", arr.dtype)

[[1.  2.  3. ]
 [4.  5.  6.2]]
Shape  (2, 3)
Dimension  2
Size  6
Datatype  float64


### Array Reshaping

In [46]:
arr = np.arange(12)
print("Original array: ", arr)
print("Shape: ", arr.shape)

reshaped = arr.reshape([3, 4])
print("Reshaped: ", reshaped)
print("Shape: ", reshaped.shape)

flatten = arr.flatten()
print("flatten: ", flatten)

#ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled: ", raveled)

# Transpose
transpose = reshaped.transpose()
print("Transpose: ", transpose)
print("Shape: ", transpose.shape)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape:  (12,)
Reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape:  (3, 4)
flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shape:  (4, 3)
