## Numpy array and basics
learn about numpy

In [3]:
import numpy as np

### creating array from list

In [7]:
arr_1d = np.array([1, 2, 3])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
end = time.time()
print("\n List operation time: ", end - start)


 List operation time:  6.080503702163696

 Numpy operation time:  0.43963122367858887


In [15]:
start_np = time.time()
np_array = np.arange(100000000) * 2
end_np = time.time()
print("\n Numpy operation time: ", end_np - start_np)


 Numpy operation time:  0.7686984539031982


### creating array from scratch

In [21]:
zeros = np.zeros((3, 4))
print("zeros array: \n",zeros)

ones = np.ones((3, 4))
print("ones array: \n",ones)

full = np.full((3, 4), 7)
print("full array: \n",full)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
