## Numpy Array operations

In [1]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array: ", arr)
print("Basic Slicing: ", arr[2: 7])
print("With step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Array:  [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing:  8


In [13]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Array 2D: ", arr_2d)
print("Specific element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 2])

Array 2D:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  6
Entire row:  [4 5 6]
Entire column:  [3 6 9]


### Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 5, 7, 1, 6])
print("Sorted Array: ", np.sort(unsorted))

Sorted Array:  [1 1 3 4 5 6 7]


In [18]:
arr_2d_unsorted = np.array([[3, 11], [2, 1], [2, 3]
                            ])
print("Sorted 2d array by column: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d array by row: ", np.sort(arr_2d_unsorted, axis=1))

Sorted 2d array by column:  [[ 2  1]
 [ 2  3]
 [ 3 11]]
Sorted 2d array by row:  [[ 3 11]
 [ 1  2]
 [ 2  3]]


### Filtering

In [20]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


### Filter with mask

In [23]:
mask = numbers > 5
print("Mask: ", mask)
print("Numbers greater than 5 ", numbers[mask])

Mask:  [False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [27]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("np.where:  ", numbers[where_result])

[1 3 5]
np.where:   [ 6  7  8  9 10]


In [33]:
condition_array = np.where(numbers > 5, 1, 0)
print(condition_array)

[0 0 0 0 0 1 1 1 1 1]


### Adding and removing data

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined_array = np.concatenate((arr1, arr2))
print(combined_array)

[1 2 3 4 5 6]


### array compatibility

In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape == c.shape)
print("Compatibility shapes", b.shape == c.shape)

Compatibility shapes True
Compatibility shapes True
Compatibility shapes True


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vs